#! /bin/bash
#
# microcebus setup begin
#


export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export TERM=xterm-256color


alias grep='grep --color=auto --line-buffered'
alias ll='ls -lh'
# alias diff='diff -Naur'
# alias patch='patch -b'
alias ec='emacs -nw'
alias dirs='dirs -v'

# echo '"\C-p": history-search-backward' >> ~/.inputrc
# bind -f ~/.inputrc


# bindkey \^U backward-kill-line
# bindkey \^. insert-last-word
# bindkey \^P history-search-backward
# bindkey \^N history-search-forward
# bindkey \^W kill-region

NORMAL="\e[0m"
WHITE="\e[0;37m"
WHITE_BOLD="\e[1;37m"
RED="\e[0;31m"
RED_BOLD="\e[1;31m"
GREEN="\e[0;32m"
GREEN_BOLD="\e[1;32m"
YELLOW="\e[0;33m"
YELLOW_BOLD="\e[1;33m"
BLUE="\e[0;34m"
BLUE_BOLD="\e[1;34m"
MAGENTA="\e[0;35m"
MAGENTA_BOLD="\e[1;35m"
CYAN="\e[0;36m"
CYAN_BOLD="\e[1;36m"

function parse_git_branch {
   git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

function pick_color() {
    if [[ $? = 0 ]]; then
	echo ":)" > /tmp/bash.face
	echo -e "\e[1;36m"
    else
	echo ":(" > /tmp/bash.face
	echo -e "\e[1;35m"
    fi
}

function get_face() {
    cat /tmp/bash.face
}


export PS1="\[\$(pick_color)\]\$(get_face)\[$BLUE_BOLD\][\A]\[$GREEN_BOLD\]\u:\[$RED_BOLD\]\w\[$YELLOW_BOLD\]\$(parse_git_branch)\[$WHITE_BOLD\] > \[$NORMAL\]"

function rm() {
    local trashbin="$HOME/.Trash"
    local args_arr=( $* )
    local files=${args_arr[@]/#-*/}
    if [[ -d $trashbin ]]; then
        cp -- $files $trashbin
    else
        mkdir -p $trashbin
        cp -- $files $trashbin
    fi
    /usr/bin/rm $*
}


#
# microcebus setup end
#
